version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitm
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI

  command-service:
    build: .
    ports:
      - "8080:80"
    environment:
      - RABBITMQ_HOST=rabbitm
    depends_on:
      - rabbitmq